version: '3'
services:
  web:
    image: php:8.2-apache
    ports:
      - '8080:80'
    depends_on:
      - mysql
    volumes:
      - /var/www/html
    networks:
      - dev-env
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: 'vincentb'
      MYSQL_PASSWORD: 'secret'
      MYSQL_DATABASE: 'vincentb'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - dev-env
  apache:
    image: httpd:latest
    ports:
      - '80:80'
    depends_on:
      - web
    networks:
      - dev-env
volumes:
  mysqldata: {}
networks:
  dev-env: {}