version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx-server-devops
    ports:
      - "8080:80"
    restart: always

  mysql:
    image: mysql:latest
    container_name: mysql-db-devops
    environment:
      MYSQL_ROOT_PASSWORD: EstoEsParaExamen
    ports:
      - "3306:3306"
    restart: always

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-devops
    environment:
      PMA_HOST: mysql-db-devops
    ports:
      - "8081:80"
    restart: always
    depends_on:
      - mysql

  redis:
    image: redis
    container_name: redis-cache-devops
    ports:
      - "6379:6379"
    restart: always

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-server-devops
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
